##################################################################
#                                                                #
# Auteur : ajt                                                   #   
#                                                                #  
# Linux practitioner | AWS Certified Cloud Practitioner          #
#                                                                #                  
##################################################################


AWSTemplateFormatVersion: 2010-09-09
Description: >-
  AWS CloudFormation Infrastructure Template for launching a WordPress website

Resources:

  ########## CREATE VPC & CIDR NOTATION

  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: true
      EnableDnsSupport: true      
      Tags:
        - Key: Name
          Value: 'ajt | VPC'

  # - LINK ROUTE TABLE 1 TO PUBLIC SUBNET 1
  AttachPublicRouteTable1:
    Type: AWS::EC2::SubnetRouteTableAssociation
      SubnetId: !Ref PublicSubnet2CIDR      


  ########## CREATE ROUTES

  PublicRoute1:
    Type: AWS::EC2::Route 
      GatewayId: !Ref ajtInternetGateway
      RouteTableId: !Ref PublicRouteTable2   

   
  ########## SECURITY GROUPS

  # - LOAD BALANCER SECURITY GROUP
  WebsiteLoadBalancerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:


  # - EC2 SECURITY GROUP
  WebsiteEC2SecurityGroup: 
    Type:  AWS::EC2::SecurityGroup
    Properties:
          ToPort: '22'                     
      VpcId: !Ref VPC
      Tags:
        - Key: Name
          Value: Website EC2 security group

  # - DATABASE SECURITY GROUP
  DataBaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup



  ########## CONTACT
 
  NotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      Subscription:
          Protocol: "email"  


  ########## CREATE BUCKET S3 & BUCKET POLICY

  BucketS3:
    Type: AWS::S3::Bucket


  ########## ELASTIC LOAD BALANCER & AUTO SCALING GROUP

  WebsiteLaunchConfig: 
    Type: AWS::AutoScaling::LaunchConfiguration
    DependsOn: DatabaseInstance  

  ########## Creates Auto Scaling Group

  WebsiteAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      - TopicARN:
          Ref: NotificationTopic
        NotificationTypes:
          - 'autoscaling:EC2_INSTANCE_LAUNCH'
          - 'autoscaling:EC2_INSTANCE_TERMINATE_ERROR'
      

  WebsiteTargetGroup: 
      Type: AWS::ElasticLoadBalancingV2::TargetGroup
      Properties: 
          Value: 300


  ########## CREATE A LISTNER ON PORT 80
  
  RouteTablePrivateSubnet:
    Type: 'AWS::EC2::RouteTable'
    Properties:

## Groupes de sécurité ##
#Réseaux publiques
  SecGrpPub:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: HTTP and SSH
      SecurityGroupIngress:
        - IpProtocol: tcp



  SSHSecGrp: 
    Type:  AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Website EC2 security group 
      SecurityGroupEgress:
          FromPort: '22'
          ToPort: '22'                     
      VpcId: !Ref VPC


## VPN ##


## Instance Intranet ##
  IntranetEC2: 
    Type: 'AWS::EC2::Instance'
    DependsOn: ConnectionRoute
    Properties:
    
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash
            sudo apt update -y

      Tags:
      - Key: Name
        Value: 'Intranet' 


